apiVersion: v1
kind: Service
metadata:
  name: ebl-chart
  labels:
    name: ebl-chart
    version: "v2"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ebl-chart
         
    version: "v2"
  type: LoadBalancer