apiVersion: apps/v1
kind: Deployment
metadata:
  name: cans
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 15 
  selector:
    matchLabels:
      app: ebl-chart
      version: "v2"
  template:
    metadata:
      labels:
        app: ebl-chart
        version: "v2"
    spec:
      containers:
      - name: ebl-chart
        image: canaryscr.azurecr.io/canary:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        #env:
        #- name: REDIS
         # value: "mhc-back"
 
